apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-hsa5
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nofn-tenant/rhtap-demo-app/hacbs-test-project-hsa5@sha256:a0bb834f021e9ba76b033013288f655c0cad9f64373a76b8fef74e1820b334a5
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
